name: Daily Run Python Script

on:
  schedule:
    # 每天GMT+2的14:00，即UTC的12:00
    - cron:  '0 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Execute Python script
      run: python update_master_list_from_urls.py
